### ISSUE TITLE
ASP.Net WebForms controls

### ISSUE THREAD

**Issue by djsmith** [aliencube/ReCaptcha.NET#2]
Hi,

Does this library work in ASP.Net WebForms page? What is the syntax to register and instantiate the recaptcha control in an aspx page?

Thanks

**Comment by justinyoo** [comment]
Hi, @djsmith 

ReCaptcha.NET currently supports razor script only. However, the wrapper itself can be used in both WebForm and MVC.

WebForm custom control for reCaptcha was not in my scope at the time of building this library.

Cheers,
