### ISSUE TITLE
Can't seem to get this to work

### ISSUE THREAD

**Issue by LlewellynJones** [aliencube/ReCaptcha.NET#4]
Is there a complete project I can download/ Not really seeing where "MVC" is defined, among other things

**Comment by justinyoo** [comment]
@LlewellynJones This repo contains a sample web app, under the SourceCodes/02_Apps/ directory. Isn't it enough for you? I also wrote a blog post for this, [http://devkimchi.com/1841/dot-net-wrapper-for-googles-new-recaptcha-api](http://devkimchi.com/1841/dot-net-wrapper-for-googles-new-recaptcha-api). HTH

**Comment by LlewellynJones** [comment]
I cloned the repository and I'm checking it out. (Just getting into the Git universe.) Thanks.
